[project]
name = "ai-code-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=2.2.6",
    "customtkinter>=5.2.2",
    "ddgs>=9.7.0",
    "google-genai>=1.48.0",
    "python-dotenv>=1.2.1",
]
